"""
MetadataExporter: Write AI-generated tags and captions back into
the original media files' EXIF / IPTC / XMP metadata.

Supports two modes:
  1. In-place write (modifies the original file)
  2. XMP sidecar write (creates a .xmp file alongside the original)

Dependencies:
  - piexif (for EXIF on JPEG)
  - Standard library only for XMP sidecar (XML)

For broader format coverage (PNG, WebP, video), the XMP sidecar
approach is recommended.
"""

import os
import json
import xml.etree.ElementTree as ET
import logging
from typing import List, Optional, Dict, Any
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class ExportableMetadata:
    """Data to be written back into a file."""
    file_path: str
    tags: List[str]
    character_tags: List[str]
    series_tags: List[str]
    caption: str


class MetadataExporter:
    """
    Writes metadata generated by Local Curator Prime into media files
    or sidecar files.
    """

    SUPPORTED_EXIF_EXT = {'.jpg', '.jpeg'}
    SUPPORTED_XMP_EXT = {'.jpg', '.jpeg', '.png', '.webp', '.bmp',
                         '.mp4', '.avi', '.mov', '.mkv', '.webm'}

    @staticmethod
    def export_to_xmp_sidecar(meta: ExportableMetadata) -> str:
        """
        Write metadata as an XMP sidecar file (.xmp) alongside the original.
        Returns the path of the created sidecar file.
        """
        base, _ = os.path.splitext(meta.file_path)
        xmp_path = base + ".xmp"

        # S7: Safely handle existing XMP files
        if os.path.exists(xmp_path):
            try:
                with open(xmp_path, 'r', encoding='utf-8') as f:
                    head = f.read(1000)
                    if "LocalCuratorPrime" not in head:
                        raise FileExistsError(f"XMP sidecar already exists and was not created by LocalCuratorPrime: {xmp_path}")
            except (IOError, UnicodeDecodeError):
                # If we couldn't read it, assume it's opaque and don't overwrite
                raise FileExistsError(f"Existing XMP sidecar found but could not be verified: {xmp_path}")

        # Build XMP XML
        root = ET.Element("x:xmpmeta", {
            "xmlns:x": "adobe:ns:meta/",
            "x:xmptk": "LocalCuratorPrime"
        })
        rdf = ET.SubElement(root, "rdf:RDF", {
            "xmlns:rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        })
        desc = ET.SubElement(rdf, "rdf:Description", {
            "rdf:about": "",
            "xmlns:dc": "http://purl.org/dc/elements/1.1/",
            "xmlns:lr": "http://ns.adobe.com/lightroom/1.0/",
        })

        # dc:description (caption)
        if meta.caption:
            dc_desc = ET.SubElement(desc, "dc:description")
            alt = ET.SubElement(dc_desc, "rdf:Alt")
            li = ET.SubElement(alt, "rdf:li", {"xml:lang": "x-default"})
            li.text = meta.caption

        # dc:subject (all tags combined as keywords)
        all_tags = meta.tags + meta.character_tags + meta.series_tags
        if all_tags:
            dc_subject = ET.SubElement(desc, "dc:subject")
            bag = ET.SubElement(dc_subject, "rdf:Bag")
            for tag in sorted(set(all_tags)):
                li = ET.SubElement(bag, "rdf:li")
                li.text = tag

        # Lightroom hierarchical tags (character → series hierarchy)
        if meta.character_tags or meta.series_tags:
            lr_hier = ET.SubElement(desc, "lr:hierarchicalSubject")
            bag = ET.SubElement(lr_hier, "rdf:Bag")
            for ch in meta.character_tags:
                li = ET.SubElement(bag, "rdf:li")
                li.text = f"Character|{ch}"
            for s in meta.series_tags:
                li = ET.SubElement(bag, "rdf:li")
                li.text = f"Series|{s}"

        tree = ET.ElementTree(root)
        ET.indent(tree, space="  ")
        tree.write(xmp_path, encoding="utf-8", xml_declaration=True)

        return xmp_path

    @staticmethod
    def export_to_exif(meta: ExportableMetadata) -> bool:
        """
        Write tags into JPEG EXIF metadata (IPTC keywords + ImageDescription).
        Returns True on success. Only works for JPEG files.
        """
        ext = os.path.splitext(meta.file_path)[1].lower()
        if ext not in MetadataExporter.SUPPORTED_EXIF_EXT:
            return False

        try:
            import piexif
        except ImportError:
            print("piexif not installed — cannot write EXIF. Use XMP sidecar instead.")
            return False

        try:
            exif_dict = piexif.load(meta.file_path)

            # ImageDescription (0th IFD, tag 270)
            if meta.caption:
                exif_dict["0th"][piexif.ImageIFD.ImageDescription] = meta.caption.encode("utf-8")

            # XPKeywords (0th IFD, tag 0x9C9E) — Windows/Explorer compatible
            all_tags = sorted(set(meta.tags + meta.character_tags + meta.series_tags))
            if all_tags:
                kw_str = ";".join(all_tags)
                exif_dict["0th"][0x9C9E] = kw_str.encode("utf-16-le")

            # Write back
            exif_bytes = piexif.dump(exif_dict)
            piexif.insert(exif_bytes, meta.file_path)
            return True

        except Exception as e:
            print(f"EXIF write error for {meta.file_path}: {e}")
            return False

    @staticmethod
    def export_batch(items: List[ExportableMetadata],
                     mode: str = "xmp") -> Dict[str, Any]:
        """
        Export metadata for multiple files.

        Args:
            items: List of ExportableMetadata to write.
            mode: "xmp" (sidecar) or "exif" (in-place JPEG only).

        Returns:
            {"success": int, "failed": int, "errors": [...]}
        """
        success = 0
        failed = 0
        errors = []

        for meta in items:
            try:
                if mode == "exif":
                    ok = MetadataExporter.export_to_exif(meta)
                    if not ok:
                        # Fallback to XMP if EXIF unsupported for this format
                        logger.info(f"EXIF not supported for {meta.file_path}, falling back to XMP sidecar")
                        MetadataExporter.export_to_xmp_sidecar(meta)
                else:
                    MetadataExporter.export_to_xmp_sidecar(meta)
                success += 1
            except Exception as e:
                failed += 1
                errors.append({"file_path": meta.file_path, "error": str(e)})

        return {"success": success, "failed": failed, "errors": errors}
